# Generated by Django 5.1.2 on 2024-10-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_document_remove_record_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='extracted_text',
        ),
    ]
