# Generated by Django 5.1.2 on 2024-10-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_customuser_delete_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
